- name: Deploy Docker containers on Cron VM
  hosts: azure_vms
  gather_facts: false
  vars:
    terraform_outputs: "{{ lookup('file', '../../terraform_outputs.json') | from_json }}"

  tasks:
    - name: Transfer setup script to VM
      ansible.builtin.copy:
        src: ./scripts/cron.sh
        dest: /home/{{ ansible_user }}/cron.sh
        mode: '0755'
      when: inventory_hostname == 'instamint-cron-vm'

    - name: Launch Docker setup script for Cron VM
      ansible.builtin.command: >
        bash /home/{{ ansible_user }}/cron.sh
        '{{ terraform_outputs.cron_config.value.username }}'
        '{{ terraform_outputs.cron_config.value.password }}'
        '{{ terraform_outputs.cron_config.value.image }}'
        '{{ terraform_outputs.cron_config.value.name }}'
        '{{ terraform_outputs.cron_config.value.port }}'
        '{{ terraform_outputs['secrets']['value']['BUSINESS-SERVICE-URL'] }}'
        '{{ terraform_outputs['secrets']['value']['REDIS-HOST'] }}'
        '{{ terraform_outputs['secrets']['value']['REDIS-PORT'] }}'
        '{{ terraform_outputs['secrets']['value']['REDIS-PASSWORD'] }}'
        '{{ terraform_outputs['secrets']['value']['SECURITY-CRON-JWT-SECRET'] }}'
        '{{ terraform_outputs['secrets']['value']['SECURITY-CRON-JWT-SCOPE-DELETE-ACCOUNT'] }}'
      register: script_output
      changed_when: "'Docker image pulled successfully.' in script_output.stdout or 'Docker container started successfully.' in script_output.stdout"
      when: inventory_hostname == 'instamint-cron-vm'
