- name: Deploy Docker containers on Files VM
  hosts: azure_vms
  gather_facts: false
  vars:
    terraform_outputs: "{{ lookup('file', '../../terraform_outputs.json') | from_json }}"

  tasks:
    - name: Transfer setup script to VM
      ansible.builtin.copy:
        src: ./scripts/files.sh
        dest: /home/{{ ansible_user }}/files.sh
        mode: '0755'
      when: inventory_hostname == 'instamint-files-vm'

    - name: Launch Docker setup script for Files VM
      ansible.builtin.command: >
        bash /home/{{ ansible_user }}/files.sh
        '{{ terraform_outputs.files_config.value.username }}'
        '{{ terraform_outputs.files_config.value.password }}'
        '{{ terraform_outputs.files_config.value.image }}'
        '{{ terraform_outputs.files_config.value.name }}'
        '{{ terraform_outputs.files_config.value.port }}'
        '{{ terraform_outputs['secrets']['value']['CORS-ORIGIN-BUSINESS'] }}'
        '{{ terraform_outputs['secrets']['value']['AZURE-ACCOUNT-NAME'] }}'
        '{{ terraform_outputs['secrets']['value']['AZURE-ACCOUNT-KEY'] }}'
        '{{ terraform_outputs['secrets']['value']['AZURE-BLOB-CONTAINER'] }}'
        '{{ terraform_outputs['secrets']['value']['AZURE-BLOB-CONNECTION'] }}'
      register: script_output
      changed_when: "'Docker image pulled successfully.' in script_output.stdout or 'Docker container started successfully.' in script_output.stdout"
      when: inventory_hostname == 'instamint-files-vm'
