version: "3.9"

services:
  instamint-webapp:
    build:
      context: .
      dockerfile: docker/Dockerfile-instamint-webapp
      target: dev
    image: docker.pkg.github.com/william-wtr92/instamint/instamint-client-webapp:dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_BLOB_URL=${NEXT_PUBLIC_BLOB_URL}
    networks:
      - instamint_network

  instamint-business:
    build:
      context: .
      dockerfile: docker/Dockerfile-instamint-business
      target: dev
    image: docker.pkg.github.com/william-wtr92/instamint/instamint-server-business:dev
    ports:
      - "3001:3001"
    environment:
      - PORT_BUSINESS=${PORT_BUSINESS}
      - DB_CONNECTION_HOST=db
      - DB_CONNECTION_USER=${DB_CONNECTION_USER_DOCKER}
      - DB_CONNECTION_PWD=${DB_CONNECTION_PASSWORD_DOCKER}
      - DB_CONNECTION_DB=${DB_CONNECTION_DOCKER}
      - REDIS_HOST=${REDIS_HOST_DOCKER}
      - REDIS_PORT=${REDIS_PORT_DOCKER}
      - REDIS_PASSWORD=${REDIS_PASSWORD_DOCKER}
      - CORS_ORIGIN=${CORS_ORIGIN_DOCKER}
      - SECURITY_COOKIE_SECRET=${SECURITY_COOKIE_SECRET}
      - SECURITY_JWT_SECRET=${SECURITY_JWT_SECRET}
      - SECURITY_PASSWORD_PEPPER=${SECURITY_PASSWORD_PEPPER}
      - SECURITY_CRON_JWT_SECRET=${SECURITY_CRON_JWT_SECRET}
      - SECURITY_CRON_JWT_SCOPE_DELETE_ACCOUNT=${SECURITY_CRON_JWT_SCOPE_DELETE_ACCOUNT}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENDGRID_BASE_URL=${SENDGRID_BASE_URL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_SENDER=${SENDGRID_SENDER}
      - SENDGRID_TEMPLATE_EMAIL_VALIDATION=${SENDGRID_TEMPLATE_EMAIL_VALIDATION}
      - SENDGRID_TEMPLATE_RESET_PASSWORD=${SENDGRID_TEMPLATE_RESET_PASSWORD}
      - SENDGRID_TEMPLATE_CONFIRM_RESET_PASSWORD=${SENDGRID_TEMPLATE_CONFIRM_RESET_PASSWORD}
      - SENDGRID_TEMPLATE_CONFIRM_ACCOUNT_DELETION=${SENDGRID_TEMPLATE_CONFIRM_ACCOUNT_DELETION}
      - SENDGRID_TEMPLATE_ACCOUNT_REACTIVATION=${SENDGRID_TEMPLATE_ACCOUNT_REACTIVATION}
      - SENDGRID_TEMPLATE_ACCOUNT_CONFIRM_REACTIVATION=${SENDGRID_TEMPLATE_ACCOUNT_CONFIRM_REACTIVATION}
      - SENDGRID_TEMPLATE_ACCOUNT_MODIFY_PASSWORD=${SENDGRID_TEMPLATE_ACCOUNT_MODIFY_PASSWORD}
      - SENDGRID_TEMPLATE_ACCOUNT_MODIFY_EMAIL=${SENDGRID_TEMPLATE_ACCOUNT_MODIFY_EMAIL}
      - FILES_SERVICE_URL=${FILES_SERVICE_URL_DOCKER}
    depends_on:
      - db
      - redis
    networks:
      - instamint_network

  instamint-files:
    build:
      context: .
      dockerfile: docker/Dockerfile-instamint-files
      target: dev
    image: docker.pkg.github.com/william-wtr92/instamint/instamint-server-files:dev
    ports:
      - "3002:3002"
    environment:
      - PORT_FILES=${PORT_FILES}
      - CORS_ORIGIN_BUSINESS_DOCKER=${CORS_ORIGIN_BUSINESS_DOCKER}
      - AZURE_ACCOUNT_NAME=${AZURE_ACCOUNT_NAME}
      - AZURE_ACCOUNT_KEY=${AZURE_ACCOUNT_KEY}
      - AZURE_BLOB_CONTAINER=${AZURE_BLOB_CONTAINER}
      - AZURE_BLOB_CONNECTION=${AZURE_BLOB_CONNECTION_DOCKER}
    networks:
      - instamint_network

  instamint-cron:
    build:
      context: .
      dockerfile: docker/Dockerfile-instamint-cron
      target: dev
    image: docker.pkg.github.com/william-wtr92/instamint/instamint-server-cron:dev
    environment:
      - BUSINESS_SERVICE_URL=${BUSINESS_SERVICE_URL_DOCKER}
      - REDIS_HOST=${REDIS_HOST_DOCKER}
      - REDIS_PORT=${REDIS_PORT_DOCKER}
      - REDIS_PASSWORD=${REDIS_PASSWORD_DOCKER}
      - SECURITY_CRON_JWT_SECRET=${SECURITY_CRON_JWT_SECRET}
      - SECURITY_CRON_JWT_SCOPE_DELETE_ACCOUNT=${SECURITY_CRON_JWT_SCOPE_DELETE_ACCOUNT}
    depends_on:
      - redis
      - instamint-business
    networks:
      - instamint_network

  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: ${DB_CONNECTION_USER_DOCKER}
      POSTGRES_PASSWORD: ${DB_CONNECTION_PASSWORD_DOCKER}
      POSTGRES_DB: ${DB_CONNECTION_DOCKER}
    ports:
      - "5432:5432"
    networks:
      - instamint_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - instamint_network

  azurite:
    image: "mcr.microsoft.com/azure-storage/azurite"
    hostname: azurite
    restart: always
    command: 'azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --location /workspace --debug /workspace/debug.log'
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./azurite:/workspace
    networks:
      - instamint_network

networks:
  instamint_network:
    driver: bridge
