FROM node:20-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable


FROM base AS build

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/ ./packages/
COPY apps/server/instamint-files/ ./apps/server/instamint-files/

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

WORKDIR /usr/src/app/apps/server/instamint-files

RUN pnpm install --frozen-lockfile

EXPOSE 3002

CMD ["pnpm", "run", "dev"]
