FROM node:20-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV PNPM_POSTINSTALL_ENABLE=false

RUN corepack enable


FROM base AS dev

WORKDIR /usr/src/app

COPY scripts/postinstall.sh ./scripts/postinstall.sh
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/ ./packages/
COPY apps/client/instamint-webapp ./apps/client/instamint-webapp

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

WORKDIR /usr/src/app/apps/client/instamint-webapp
RUN pnpm install --frozen-lockfile

EXPOSE 3000

CMD ["pnpm", "run", "dev"]


FROM base AS prod

WORKDIR /usr/src/app

COPY scripts/postinstall.sh ./scripts/postinstall.sh
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/eslint/client/ ./packages/eslint/client/
COPY packages/tsconfig/client/ ./packages/tsconfig/client/
COPY apps/client/instamint-webapp ./apps/client/instamint-webapp

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

WORKDIR /usr/src/app/apps/client/instamint-webapp
RUN pnpm install --prod
RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "run", "start"]
