profile: null

exclude_paths:
  - .cache/
  - test/fixtures/formatting-before/
  - test/fixtures/formatting-prettier/

mock_modules:
  - zuul_return
  - fake_namespace.fake_collection.fake_module
  - fake_namespace.fake_collection.fake_module.fake_submodule
mock_roles:
  - mocked_role
  - author.role_name
  - fake_namespace.fake_collection.fake_role

loop_var_prefix: "^(__|{role}_)"

var_naming_pattern: "^[a-z_][a-z0-9_]*$"

use_default_rules: true

skip_list:
  - skip_this_tag

enable_list:
  - args
  - empty-string-compare # opt-in
  - no-log-password # opt-in
  - no-same-owner # opt-in
  - name[prefix] # opt-in
  - yaml

warn_list:
  - skip_this_tag
  - experimental

offline: true

extra_vars:
  foo: bar
  multiline_string_variable: |
    line1
    line2
  complex_variable: ":{;\t$()"


kinds:
  - yaml: "**/*.yaml-too"

task_name_prefix: "{stem} | "
