import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Instamint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center h-screen">
        <h1 className="font-bold text-6xl">👀 Instamint WIP ! </h1>
      </main>
    </>
  )
}
