{
 "title": "Azure Infra",
 "description": "Azure Redis",
 "tags": [ "azure" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "VMs CPU ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "region": "francecentral",
        "resourceGroup": "instamint",
        "resourceName": "instamint-business-vm",
        "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
       },
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "francecentral",
        "resourceGroup": "instamint",
        "resourceName": "instamint-cron-vm",
        "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
       },
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "francecentral",
        "resourceGroup": "instamint",
        "resourceName": "instamint-files-vm",
        "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
       },
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "francecentral",
        "resourceGroup": "instamint",
        "resourceName": "instamint-webapp-vm",
        "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
    }
   ]
  },
  {
   "title": "Blob Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.Storage/storageAccounts",
        "region": "francecentral",
        "resourceGroup": "instamint",
        "resourceName": "instamintstoragef851907d",
        "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "timeseries",
   "description": "Redis Operations",
   "gridPos": { "h": 9, "w": 12, "x": 8, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "totalcommandsprocessed",
      "metricNamespace": "microsoft.cache/redis",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.Cache/Redis",
        "region": "francecentral",
        "resourceGroup": "instamint",
        "resourceName": "instamint-redis",
        "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "serverLoad",
      "metricNamespace": "microsoft.cache/redis",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.Cache/Redis",
        "region": "francecentral",
        "resourceGroup": "instamint",
        "resourceName": "instamint-redis",
        "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
    }
   ]
  },
  {
   "title": "Key Vault",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServiceApiHit",
      "metricNamespace": "microsoft.keyvault/vaults",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.KeyVault/vaults",
        "region": "francecentral",
        "resourceGroup": "instamint",
        "resourceName": "instamint-kv-f851907d",
        "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage_used",
      "metricNamespace": "microsoft.dbforpostgresql/servers",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/servers",
        "region": "francecentral",
        "resourceGroup": "instamint",
        "resourceName": "instamint-postgres",
        "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "memory_percent",
      "metricNamespace": "microsoft.dbforpostgresql/servers",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforPostgreSQL/servers",
        "region": "francecentral",
        "resourceGroup": "instamint",
        "resourceName": "instamint-postgres",
        "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
    }
   ]
  },
  {
   "title": "ACR",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SuccessfulPushCount",
      "metricNamespace": "microsoft.containerregistry/registries",
      "region": "francecentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerRegistry/registries",
        "region": "francecentral",
        "resourceGroup": "instamint",
        "resourceName": "instamintACR",
        "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "821952a0-1ce2-493d-83b6-5838b231e550"
    }
   ]
  }
 ]
}