- name: Install Docker on all VMs
  hosts: all
  become: yes

  tasks:
    - name: Transfer Docker install script
      copy:
        src: ./scripts/install.sh
        dest: /home/{{ ansible_user }}/install.sh
        mode: 0755

    - name: Execute Docker install script
      command: bash /home/{{ ansible_user }}/install.sh