- name: Base Installation for VMs
  import_playbook: "./vms/launch.yml"

- name: Deploy Docker containers on Webapp VM
  import_playbook: "./vms/webapp.yml"

- name: Deploy Docker containers on Cron VM
  import_playbook: "./vms/business.yml"

- name: Deploy Docker containers on Files VM
  import_playbook: "./vms/files.yml"

- name: Deploy Docker containers on Cron VM
  import_playbook: "./vms/cron.yml"
